# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='deleted_on',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_deleted',
        ),
    ]
