# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 23:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20180926_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='banned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banned_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
